version: "3.8"

services:
  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: "leaderboard"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - leaderboard:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  leaderboard:
